services:
  backupbot:
    image: gitea.calahilstudios.com/calahil/backupbot:latest
    container_name: backupbot
    privileged: true
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Los_Angeles
      - SETTINGS_ENCRYPTION_KEY=${KEY}
      - CLI_ARGS= #optional
      - DUPLICATI__WEBSERVICE_PASSWORD=${PASSWORD}
    volumes:
      # Config dir for duplicati
      - /srv/appdata/duplicati/config:/config
      # Backup folder to store dumps/backups/snapshots
      - /srv/backups:/backups
      # Docker socket to list containers
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8200:8200
      - 8201:8080
    restart: unless-stopped
