services:
  backupbot:
    image: gitea.calahilstudios.com/calahil/backupbot:latest
    container_name: backupbot
    privileged: true
    environment:
      - TZ=Etc/UTC
    volumes:
      # Backup folder to store dumps (accessible by Duplicati)
      - /srv/backups:/backups
      # Local docker config dirs
      - /srv/appdata:/source/appdata:rshared
      # Docker socket to list containers
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
