name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build:
    runs-on: prodesk
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Gitea Docker Registry
        uses: docker/login-action@v3
        with:
          registry: gitea.calahilstudios.com
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            gitea.calahilstudios.com/${{ github.repository_owner }}/${{ github.event.repository.name }}:develop
            gitea.calahilstudios.com/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}
